apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    # alb.ingress.kubernetes.io/healthcheck-port: '443'
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:089143290485:certificate/8f20bc85-876b-47a2-8c9f-27e9f5455ca9"
    external-dns.alpha.kubernetes.io/hostname: "*.so1s.io"
spec:
  defaultBackend:
    service:
      name: istio-gateway
      port:
        number: 80
  rules:
    - http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: istio-gateway
              port:
                number: 80