apiVersion: v2
appVersion: 1.15.3
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
  - gateways
name: istio-gateway
sources:
  - http://github.com/istio/istio
type: application
version: 1.15.3
