apiVersion: v1
appVersion: 1.14.2
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
name: istio-base
sources:
  - http://github.com/istio/istio
version: 1.14.2
